import { getMobile } from '../../util/auth'
export default {
  notice: '',
  noticePre: {},
  noticeAft: {},
  news: '',
  newsPre: {},
  newsAft: {},
  healthy: '',
  healthyPre: {},
  healthyAft: {},
  loading: false,
  bannerList: [],
  noticeList: {},
  newsList: {},
  healthyList: {},
  doctorList: {},
  envList: {},
  selectList1: [],
  selectList2: [],
  selectList3: [],
  envAllList: [],
  doctorAll: [],
  sectionInfo: '',
  sectionDoctors: [],
  userInfo: '',
  mobile: getMobile()
}
